INSERT INTO byb_traits (trait, tagline) 
VALUES
("Humility", "Take up the right amount of space"), 
("Patience",	"This moment also is okay"), 
("Gratitude", "Express thanks for the good"),  
("Compassion", "Be close to feel what the other feels"), 
("Order", "Take time, be exact, unclutter the mind"), 
("Equanimity", "The even-keeled will stay true to course"), 
("Respect", "Honor the holiness in self and other"), 
("Simplicity", "What I have is enough"), 
("Enthusiasm", "YES I will do that!"), 
("Silence", "Be still, pay attention, what more is needed?"), 
("Generosity", "The generous heart gives freely"), 
("Truth", "The truth lies deep in the heart"), 
("Balance", "Everything in moderation, including moderation"), 
("Kindness", "A Loving kindess will light the way"), 
("Responsibility", "Responsibility is at the core of relationship"), 
("Trust", "To swim, you must jup in"), 
("Faith", "The body needs air, the soul need faith"), 
("Wonder", "How Amazing is that!"), 
("Hope", "Hope is born from imagination"), 
("Courage", "Open the greatness within"), 
("Resillience", "To fall 7 times, but get up 8!"), 
("Hospitality", "There is always room for more"), 
("Flexibility", "Both these and those are the path to truth") 